# Generated by Django 3.2.12 on 2022-02-21 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220221_0425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caretaker',
            old_name='userid',
            new_name='userID',
        ),
    ]
