# Generated by Django 3.2.12 on 2022-02-21 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('roleid', models.AutoField(db_column='roleID', primary_key=True, serialize=False)),
                ('rolename', models.CharField(db_column='roleName', max_length=30)),
            ],
            options={
                'db_table': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Securityquestions',
            fields=[
                ('securityquestionid', models.AutoField(db_column='securityQuestionID', primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'SecurityQuestions',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(db_column='userID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, db_column='firstName', max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, db_column='lastName', max_length=50, null=True)),
                ('phoneNumber', models.DecimalField(blank=True, db_column='phoneNumber', decimal_places=0, max_digits=10, null=True)),
                ('postalAddress', models.CharField(blank=True, db_column='postalAddress', max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(db_column='userName', max_length=100)),
                ('pwd', models.CharField(max_length=32)),
                ('securityquestiononeanswer', models.CharField(blank=True, db_column='securityQuestionOneAnswer', max_length=30, null=True)),
                ('securityquestiontwoanswer', models.CharField(blank=True, db_column='securityQuestionTwoAnswer', max_length=30, null=True)),
                ('securityquestionthreeanswer', models.CharField(blank=True, db_column='securityQuestionThreeAnswer', max_length=30, null=True)),
                ('roleId', models.ForeignKey(db_column='roleID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.roles')),
                ('securityquestiononeid', models.ForeignKey(blank=True, db_column='securityQuestionOneID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='q1', to='api.securityquestions')),
                ('securityquestionthreeid', models.ForeignKey(blank=True, db_column='securityQuestionThreeID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='q3', to='api.securityquestions')),
                ('securityquestiontwoid', models.ForeignKey(blank=True, db_column='securityQuestionTwoID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='q2', to='api.securityquestions')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('requestid', models.IntegerField(db_column='requestID', primary_key=True, serialize=False)),
                ('patientfirstname', models.CharField(db_column='patientFirstName', max_length=50)),
                ('patientlastname', models.CharField(db_column='patientLastName', max_length=50)),
                ('sex', models.CharField(max_length=1)),
                ('dateofbirth', models.DateField(db_column='dateOfBirth')),
                ('locationofservice', models.CharField(db_column='locationOfService', max_length=30)),
                ('patientphonenumber', models.DecimalField(db_column='patientPhoneNumber', decimal_places=0, max_digits=10)),
                ('patientemail', models.CharField(db_column='patientEmail', max_length=100)),
                ('servicetype', models.CharField(db_column='serviceType', max_length=10)),
                ('daysrequested', models.CharField(blank=True, db_column='daysRequested', max_length=10, null=True)),
                ('starttime', models.TimeField(blank=True, db_column='startTime', null=True)),
                ('endtime', models.TimeField(blank=True, db_column='endTime', null=True)),
                ('numdaysrequested', models.IntegerField(blank=True, db_column='numDaysRequested', null=True)),
                ('userid', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.users')),
            ],
            options={
                'db_table': 'Requests',
            },
        ),
        migrations.CreateModel(
            name='Healthcareprofessional',
            fields=[
                ('pid', models.IntegerField(db_column='PID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='firstName', max_length=50)),
                ('lastname', models.CharField(db_column='lastName', max_length=50)),
                ('sex', models.CharField(max_length=1)),
                ('ssn', models.DecimalField(db_column='SSN', decimal_places=0, max_digits=9)),
                ('type_h_s', models.CharField(db_column='Type_H_S', max_length=15)),
                ('qualification', models.CharField(db_column='Qualification', max_length=10)),
                ('qualification_date', models.DateField(db_column='Qualification_Date')),
                ('year_o_exp', models.IntegerField(db_column='Year_O_Exp')),
                ('phonenumber', models.DecimalField(blank=True, db_column='phoneNumber', decimal_places=0, max_digits=10, null=True)),
                ('postaladdress', models.CharField(blank=True, db_column='postalAddress', max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('enroll', models.TextField(blank=True, null=True)),
                ('userid', models.ForeignKey(blank=True, db_column='userID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.users')),
            ],
            options={
                'db_table': 'HealthcareProfessional',
            },
        ),
        migrations.CreateModel(
            name='Caretaker',
            fields=[
                ('takerid', models.AutoField(db_column='takerID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='firstName', max_length=50)),
                ('lastname', models.CharField(db_column='lastName', max_length=50)),
                ('phonenumber', models.DecimalField(blank=True, db_column='phoneNumber', decimal_places=0, max_digits=10, null=True)),
                ('postaladdress', models.CharField(blank=True, db_column='postalAddress', max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('enroll', models.TextField(blank=True, null=True)),
                ('userid', models.ForeignKey(blank=True, db_column='userID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.users')),
            ],
            options={
                'db_table': 'CareTaker',
            },
        ),
    ]
